
void* malloc(size_t);
void free(void* ptr);

typedef INT32 BOOL;			/* Boolean */
typedef WCHAR XCHAR;			/* Wide Character */
typedef INT32 RW;			/* XL 12 Row */
typedef INT32 COL;	 	      	/* XL 12 Column */
typedef DWORD_PTR IDSHEET;		/* XL12 Sheet ID */

/*
** XLREF structure
**
** Describes a single rectangular reference.
*/

typedef struct xlref
{
	WORD rwFirst;
	WORD rwLast;
	BYTE colFirst;
	BYTE colLast;
} XLREF, *LPXLREF;


/*
** XLMREF structure
**
** Describes multiple rectangular references.
** This is a variable size structure, default
** size is 1 reference.
*/

typedef struct xlmref
{
	WORD count;
	XLREF reftbl[1];					/* actually reftbl[count] */
} XLMREF, *LPXLMREF;


/*
** XLREF12 structure
**
** Describes a single XL 12 rectangular reference.
*/

typedef struct xlref12
{
	RW rwFirst;
	RW rwLast;
	COL colFirst;
	COL colLast;
} XLREF12, *LPXLREF12;


/*
** XLMREF12 structure
**
** Describes multiple rectangular XL 12 references.
** This is a variable size structure, default
** size is 1 reference.
*/

typedef struct xlmref12
{
	WORD count;
	XLREF12 reftbl[1];					/* actually reftbl[count] */
} XLMREF12, *LPXLMREF12;


/*
** FP structure
**
** Describes FP structure.
*/

typedef struct _FP
{
    unsigned short int rows;
    unsigned short int columns;
    double array[1];        /* Actually, array[rows][columns] */
} FP;

/*
** FP12 structure
**
** Describes FP structure capable of handling the big grid.
*/

typedef struct _FP12
{
    INT32 rows;
    INT32 columns;
    double array[1];        /* Actually, array[rows][columns] */
} FP12;


/*
** XLOPER structure
**
** Excel's fundamental data type: can hold data
** of any type. Use "R" as the argument type in the
** REGISTER function.
**/

typedef struct xloper
{
	union
	{
		double num;					/* xltypeNum */
		LPSTR str;					/* xltypeStr */
		WORD bool;					/* xltypeBool */
		WORD err;					/* xltypeErr */
		short int w;					/* xltypeInt */
		struct
		{
			WORD count;				/* always = 1 */
			XLREF ref;
		} sref;						/* xltypeSRef */
		struct
		{
			XLMREF *lpmref;
			IDSHEET idSheet;
		} mref;						/* xltypeRef */
		struct
		{
			struct xloper *lparray;
			WORD rows;
			WORD columns;
		} array;					/* xltypeMulti */
		struct
		{
			union
			{
				short int level;		/* xlflowRestart */
				short int tbctrl;		/* xlflowPause */
				IDSHEET idSheet;		/* xlflowGoto */
			} valflow;
			WORD rw;				/* xlflowGoto */
			BYTE col;				/* xlflowGoto */
			BYTE xlflow;
		} flow;						/* xltypeFlow */
		struct
		{
			union
			{
				BYTE *lpbData;			/* data passed to XL */
				HANDLE hdata;			/* data returned from XL */
			} h;
			long cbData;
		} bigdata;					/* xltypeBigData */
	} val;
	WORD xltype;
} XLOPER, *LPXLOPER;


/*
** XLOPER12 structure
**
** Excel 12's fundamental data type: can hold data
** of any type. Use "U" as the argument type in the
** REGISTER function.
**/

typedef struct xloper12
{
	union
	{
		double num;				       	/* xltypeNum */
		XCHAR *str;				       	/* xltypeStr */
		BOOL xbool;				       	/* xltypeBool */
		int err;				       	/* xltypeErr */
		int w;
		struct
		{
			WORD count;			       	/* always = 1 */
			XLREF12 ref;
		} sref;						/* xltypeSRef */
		struct
		{
			XLMREF12 *lpmref;
			IDSHEET idSheet;
		} mref;						/* xltypeRef */
		struct
		{
			struct xloper12 *lparray;
			RW rows;
			COL columns;
		} array;					/* xltypeMulti */
		struct
		{
			union
			{
				int level;			/* xlflowRestart */
				int tbctrl;			/* xlflowPause */
				IDSHEET idSheet;		/* xlflowGoto */
			} valflow;
			RW rw;				       	/* xlflowGoto */
			COL col;			       	/* xlflowGoto */
			BYTE xlflow;
		} flow;						/* xltypeFlow */
		struct
		{
			union
			{
				BYTE *lpbData;			/* data passed to XL */
				HANDLE hdata;			/* data returned from XL */
			} h;
			long cbData;
		} bigdata;					/* xltypeBigData */
	} val;
	DWORD xltype;
} XLOPER12, *LPXLOPER12;

#define xltypeNum ...
#define xltypeStr ...
#define xltypeBool ...
#define xltypeRef ...
#define xltypeErr ...
#define xltypeFlow ...
#define xltypeMulti ...
#define xltypeMissing ...
#define xltypeNil ...
#define xltypeSRef ...
#define xltypeInt ...

#define xlbitXLFree ...
#define xlbitDLLFree ...

#define xltypeBigData ...


/*
** Error codes
**
** Used for val.err field of XLOPER and XLOPER12 structures
** when constructing error XLOPERs and XLOPER12s
*/

#define xlerrNull ...
#define xlerrDiv0 ...
#define xlerrValue ...
#define xlerrRef ...
#define xlerrName ...
#define xlerrNum ...
#define xlerrNA ...
#define xlerrGettingData ...


/*
** Flow data types
**
** Used for val.flow.xlflow field of XLOPER and XLOPER12 structures
** when constructing flow-control XLOPERs and XLOPER12s
**/

#define xlflowHalt ...
#define xlflowGoto ...
#define xlflowRestart ...
#define xlflowPause ...
#define xlflowResume ...

/*
** Return codes
**
** These values can be returned from Excel4(), Excel4v(), Excel12() or Excel12v().
*/

#define xlretSuccess ...
#define xlretAbort ...
#define xlretInvXlfn ...
#define xlretInvCount ...
#define xlretInvXloper ...
#define xlretStackOvfl ...
#define xlretFailed ...
#define xlretUncalced ...
#define xlretNotThreadSafe ...
#define xlretInvAsynchronousContext ...
#define xlretNotClusterSafe ...


/*
** XLL events
**
** Passed in to an xlEventRegister call to register a corresponding event.
*/

#define xleventCalculationEnded ...
#define xleventCalculationCanceled ...



/*
** Cluster Connector Async Callback
*/

// typedef int (CALLBACK *PXL_HPC_ASYNC_CALLBACK)(LPXLOPER12 operAsyncHandle, LPXLOPER12 operReturn);


/*
** Cluster connector entry point return codes
*/

//#define xlHpcRetSuccess ...
//#define xlHpcRetSessionIdInvalid ...
//#define xlHpcRetCallFailed ...


/*
** Function number bits
*/

#define xlCommand ...
#define xlSpecial ...
#define xlIntl ...
#define xlPrompt ...


/*
** Auxiliary function numbers
**
** These functions are available only from the C API,
** not from the Excel macro language.
*/

#define xlFree ...
#define xlStack ...
#define xlCoerce ...
#define xlSet ...
#define xlSheetId ...
#define xlSheetNm ...
#define xlAbort ...
#define xlGetInst ...
#define xlGetHwnd ...
#define xlGetName ...
#define xlEnableXLMsgs ...
#define xlDisableXLMsgs ...
#define xlDefineBinaryName ...
#define xlGetBinaryName ...
/* GetFooInfo are valid only for calls to LPenHelper */
#define xlGetFmlaInfo ...
#define xlGetMouseInfo ...
#define xlAsyncReturn ...
#define xlEventRegister ...
#define xlRunningOnCluster ...
#define xlGetInstPtr ...

/* edit modes */
#define xlModeReady ...
#define xlModeEnter ...
#define xlModeEdit ...
#define xlModePoint ...

/* document(page) types */
#define dtNil ...
// OR window is not the selected window at idle state
#define dtSheet ...
#define dtProc ...
#define dtChart ...
#define dtBasic ...

/* hit test codes */
#define htNone ...
#define htClient ...
#define htVSplit ...
#define htHSplit ...
#define htColWidth ...
#define htRwHeight ...
#define htRwColHdr ...
#define htObject ...
// the following are for size handles of draw objects
#define htTopLeft ...
#define htBotLeft ...
#define htLeft ...
#define htTopRight ...
#define htBotRight ...
#define htRight ...
#define htTop ...
#define htBot ...
// end size handles
#define htRwGut ...
#define htColGut ...
#define htTextBox ...
#define htRwLevels ...
#define htColLevels ...
#define htDman ...
#define htDmanFill ...
#define htXSplit ...
#define htVertex ...
#define htAddVtx ...
#define htDelVtx ...
#define htRwHdr ...
#define htColHdr ...
#define htRwShow ...
#define htColShow ...
#define htSizing ...
#define htSxpivot ...
#define htTabs ...
#define htEdit ...

//typedef struct _fmlainfo
//{
//	int wPointMode;	// current edit mode.  0 => rest of struct undefined
//	int cch;	// count of characters in formula
//	char *lpch;	// pointer to formula characters.  READ ONLY!!!
//	int ichFirst;	// char offset to start of selection
//	int ichLast;	// char offset to end of selection (may be > cch)
//	int ichCaret;	// char offset to blinking caret
//} FMLAINFO;
//
//typedef struct _mouseinfo
//{
//	/* input section */
//	HWND hwnd;		// window to get info on
//	POINT pt;		// mouse position to get info on
//
//	/* output section */
//	int dt;			// document(page) type
//	int ht;			// hit test code
//	int rw;			// row @ mouse (-1 if #n/a)
//	int col;		// col @ mouse (-1 if #n/a)
//} MOUSEINFO;
//


/*
** User defined function
**
** First argument should be a function reference.
*/

#define xlUDF ...


/*
** Built-in Excel functions and command equivalents
*/


// Excel function numbers

#define xlfCount ...
#define xlfIsna ...
#define xlfIserror ...
#define xlfSum ...
#define xlfAverage ...
#define xlfMin ...
#define xlfMax ...
#define xlfRow ...
#define xlfColumn ...
#define xlfNa ...
#define xlfNpv ...
#define xlfStdev ...
#define xlfDollar ...
#define xlfFixed ...
#define xlfSin ...
#define xlfCos ...
#define xlfTan ...
#define xlfAtan ...
#define xlfPi ...
#define xlfSqrt ...
#define xlfExp ...
#define xlfLn ...
#define xlfLog10 ...
#define xlfAbs ...
#define xlfInt ...
#define xlfSign ...
#define xlfRound ...
#define xlfLookup ...
#define xlfIndex ...
#define xlfRept ...
#define xlfMid ...
#define xlfLen ...
#define xlfValue ...
#define xlfTrue ...
#define xlfFalse ...
#define xlfAnd ...
#define xlfOr ...
#define xlfNot ...
#define xlfMod ...
#define xlfDcount ...
#define xlfDsum ...
#define xlfDaverage ...
#define xlfDmin ...
#define xlfDmax ...
#define xlfDstdev ...
#define xlfVar ...
#define xlfDvar ...
#define xlfText ...
#define xlfLinest ...
#define xlfTrend ...
#define xlfLogest ...
#define xlfGrowth ...
#define xlfGoto ...
#define xlfHalt ...
#define xlfPv ...
#define xlfFv ...
#define xlfNper ...
#define xlfPmt ...
#define xlfRate ...
#define xlfMirr ...
#define xlfIrr ...
#define xlfRand ...
#define xlfMatch ...
#define xlfDate ...
#define xlfTime ...
#define xlfDay ...
#define xlfMonth ...
#define xlfYear ...
#define xlfWeekday ...
#define xlfHour ...
#define xlfMinute ...
#define xlfSecond ...
#define xlfNow ...
#define xlfAreas ...
#define xlfRows ...
#define xlfColumns ...
#define xlfOffset ...
#define xlfAbsref ...
#define xlfRelref ...
#define xlfArgument ...
#define xlfSearch ...
#define xlfTranspose ...
#define xlfError ...
#define xlfStep ...
#define xlfType ...
#define xlfEcho ...
#define xlfSetName ...
#define xlfCaller ...
#define xlfDeref ...
#define xlfWindows ...
#define xlfSeries ...
#define xlfDocuments ...
#define xlfActiveCell ...
#define xlfSelection ...
#define xlfResult ...
#define xlfAtan2 ...
#define xlfAsin ...
#define xlfAcos ...
#define xlfChoose ...
#define xlfHlookup ...
#define xlfVlookup ...
#define xlfLinks ...
#define xlfInput ...
#define xlfIsref ...
#define xlfGetFormula ...
#define xlfGetName ...
#define xlfSetValue ...
#define xlfLog ...
#define xlfExec ...
#define xlfChar ...
#define xlfLower ...
#define xlfUpper ...
#define xlfProper ...
#define xlfLeft ...
#define xlfRight ...
#define xlfExact ...
#define xlfTrim ...
#define xlfReplace ...
#define xlfSubstitute ...
#define xlfCode ...
#define xlfNames ...
#define xlfDirectory ...
#define xlfFind ...
#define xlfCell ...
#define xlfIserr ...
#define xlfIstext ...
#define xlfIsnumber ...
#define xlfIsblank ...
#define xlfT ...
#define xlfN ...
#define xlfFopen ...
#define xlfFclose ...
#define xlfFsize ...
#define xlfFreadln ...
#define xlfFread ...
#define xlfFwriteln ...
#define xlfFwrite ...
#define xlfFpos ...
#define xlfDatevalue ...
#define xlfTimevalue ...
#define xlfSln ...
#define xlfSyd ...
#define xlfDdb ...
#define xlfGetDef ...
#define xlfReftext ...
#define xlfTextref ...
#define xlfIndirect ...
#define xlfRegister ...
#define xlfCall ...
#define xlfAddBar ...
#define xlfAddMenu ...
#define xlfAddCommand ...
#define xlfEnableCommand ...
#define xlfCheckCommand ...
#define xlfRenameCommand ...
#define xlfShowBar ...
#define xlfDeleteMenu ...
#define xlfDeleteCommand ...
#define xlfGetChartItem ...
#define xlfDialogBox ...
#define xlfClean ...
#define xlfMdeterm ...
#define xlfMinverse ...
#define xlfMmult ...
#define xlfFiles ...
#define xlfIpmt ...
#define xlfPpmt ...
#define xlfCounta ...
#define xlfCancelKey ...
#define xlfInitiate ...
#define xlfRequest ...
#define xlfPoke ...
#define xlfExecute ...
#define xlfTerminate ...
#define xlfRestart ...
#define xlfHelp ...
#define xlfGetBar ...
#define xlfProduct ...
#define xlfFact ...
#define xlfGetCell ...
#define xlfGetWorkspace ...
#define xlfGetWindow ...
#define xlfGetDocument ...
#define xlfDproduct ...
#define xlfIsnontext ...
#define xlfGetNote ...
#define xlfNote ...
#define xlfStdevp ...
#define xlfVarp ...
#define xlfDstdevp ...
#define xlfDvarp ...
#define xlfTrunc ...
#define xlfIslogical ...
#define xlfDcounta ...
#define xlfDeleteBar ...
#define xlfUnregister ...
#define xlfUsdollar ...
#define xlfFindb ...
#define xlfSearchb ...
#define xlfReplaceb ...
#define xlfLeftb ...
#define xlfRightb ...
#define xlfMidb ...
#define xlfLenb ...
#define xlfRoundup ...
#define xlfRounddown ...
#define xlfAsc ...
#define xlfDbcs ...
#define xlfRank ...
#define xlfAddress ...
#define xlfDays360 ...
#define xlfToday ...
#define xlfVdb ...
#define xlfMedian ...
#define xlfSumproduct ...
#define xlfSinh ...
#define xlfCosh ...
#define xlfTanh ...
#define xlfAsinh ...
#define xlfAcosh ...
#define xlfAtanh ...
#define xlfDget ...
#define xlfCreateObject ...
#define xlfVolatile ...
#define xlfLastError ...
#define xlfCustomUndo ...
#define xlfCustomRepeat ...
#define xlfFormulaConvert ...
#define xlfGetLinkInfo ...
#define xlfTextBox ...
#define xlfInfo ...
#define xlfGroup ...
#define xlfGetObject ...
#define xlfDb ...
#define xlfPause ...
#define xlfResume ...
#define xlfFrequency ...
#define xlfAddToolbar ...
#define xlfDeleteToolbar ...
#define xlfResetToolbar ...
#define xlfEvaluate ...
#define xlfGetToolbar ...
#define xlfGetTool ...
#define xlfSpellingCheck ...
#define xlfErrorType ...
#define xlfAppTitle ...
#define xlfWindowTitle ...
#define xlfSaveToolbar ...
#define xlfEnableTool ...
#define xlfPressTool ...
#define xlfRegisterId ...
#define xlfGetWorkbook ...
#define xlfAvedev ...
#define xlfBetadist ...
#define xlfGammaln ...
#define xlfBetainv ...
#define xlfBinomdist ...
#define xlfChidist ...
#define xlfChiinv ...
#define xlfCombin ...
#define xlfConfidence ...
#define xlfCritbinom ...
#define xlfEven ...
#define xlfExpondist ...
#define xlfFdist ...
#define xlfFinv ...
#define xlfFisher ...
#define xlfFisherinv ...
#define xlfFloor ...
#define xlfGammadist ...
#define xlfGammainv ...
#define xlfCeiling ...
#define xlfHypgeomdist ...
#define xlfLognormdist ...
#define xlfLoginv ...
#define xlfNegbinomdist ...
#define xlfNormdist ...
#define xlfNormsdist ...
#define xlfNorminv ...
#define xlfNormsinv ...
#define xlfStandardize ...
#define xlfOdd ...
#define xlfPermut ...
#define xlfPoisson ...
#define xlfTdist ...
#define xlfWeibull ...
#define xlfSumxmy2 ...
#define xlfSumx2my2 ...
#define xlfSumx2py2 ...
#define xlfChitest ...
#define xlfCorrel ...
#define xlfCovar ...
#define xlfForecast ...
#define xlfFtest ...
#define xlfIntercept ...
#define xlfPearson ...
#define xlfRsq ...
#define xlfSteyx ...
#define xlfSlope ...
#define xlfTtest ...
#define xlfProb ...
#define xlfDevsq ...
#define xlfGeomean ...
#define xlfHarmean ...
#define xlfSumsq ...
#define xlfKurt ...
#define xlfSkew ...
#define xlfZtest ...
#define xlfLarge ...
#define xlfSmall ...
#define xlfQuartile ...
#define xlfPercentile ...
#define xlfPercentrank ...
#define xlfMode ...
#define xlfTrimmean ...
#define xlfTinv ...
#define xlfMovieCommand ...
#define xlfGetMovie ...
#define xlfConcatenate ...
#define xlfPower ...
#define xlfPivotAddData ...
#define xlfGetPivotTable ...
#define xlfGetPivotField ...
#define xlfGetPivotItem ...
#define xlfRadians ...
#define xlfDegrees ...
#define xlfSubtotal ...
#define xlfSumif ...
#define xlfCountif ...
#define xlfCountblank ...
#define xlfScenarioGet ...
#define xlfOptionsListsGet ...
#define xlfIspmt ...
#define xlfDatedif ...
#define xlfDatestring ...
#define xlfNumberstring ...
#define xlfRoman ...
#define xlfOpenDialog ...
#define xlfSaveDialog ...
#define xlfViewGet ...
#define xlfGetpivotdata ...
#define xlfHyperlink ...
#define xlfPhonetic ...
#define xlfAveragea ...
#define xlfMaxa ...
#define xlfMina ...
#define xlfStdevpa ...
#define xlfVarpa ...
#define xlfStdeva ...
#define xlfVara ...
#define xlfBahttext ...
#define xlfThaidayofweek ...
#define xlfThaidigit ...
#define xlfThaimonthofyear ...
#define xlfThainumsound ...
#define xlfThainumstring ...
#define xlfThaistringlength ...
#define xlfIsthaidigit ...
#define xlfRoundbahtdown ...
#define xlfRoundbahtup ...
#define xlfThaiyear ...
#define xlfRtd ...
#define xlfCubevalue ...
#define xlfCubemember ...
#define xlfCubememberproperty ...
#define xlfCuberankedmember ...
#define xlfHex2bin ...
#define xlfHex2dec ...
#define xlfHex2oct ...
#define xlfDec2bin ...
#define xlfDec2hex ...
#define xlfDec2oct ...
#define xlfOct2bin ...
#define xlfOct2hex ...
#define xlfOct2dec ...
#define xlfBin2dec ...
#define xlfBin2oct ...
#define xlfBin2hex ...
#define xlfImsub ...
#define xlfImdiv ...
#define xlfImpower ...
#define xlfImabs ...
#define xlfImsqrt ...
#define xlfImln ...
#define xlfImlog2 ...
#define xlfImlog10 ...
#define xlfImsin ...
#define xlfImcos ...
#define xlfImexp ...
#define xlfImargument ...
#define xlfImconjugate ...
#define xlfImaginary ...
#define xlfImreal ...
#define xlfComplex ...
#define xlfImsum ...
#define xlfImproduct ...
#define xlfSeriessum ...
#define xlfFactdouble ...
#define xlfSqrtpi ...
#define xlfQuotient ...
#define xlfDelta ...
#define xlfGestep ...
#define xlfIseven ...
#define xlfIsodd ...
#define xlfMround ...
#define xlfErf ...
#define xlfErfc ...
#define xlfBesselj ...
#define xlfBesselk ...
#define xlfBessely ...
#define xlfBesseli ...
#define xlfXirr ...
#define xlfXnpv ...
#define xlfPricemat ...
#define xlfYieldmat ...
#define xlfIntrate ...
#define xlfReceived ...
#define xlfDisc ...
#define xlfPricedisc ...
#define xlfYielddisc ...
#define xlfTbilleq ...
#define xlfTbillprice ...
#define xlfTbillyield ...
#define xlfPrice ...
#define xlfYield ...
#define xlfDollarde ...
#define xlfDollarfr ...
#define xlfNominal ...
#define xlfEffect ...
#define xlfCumprinc ...
#define xlfCumipmt ...
#define xlfEdate ...
#define xlfEomonth ...
#define xlfYearfrac ...
#define xlfCoupdaybs ...
#define xlfCoupdays ...
#define xlfCoupdaysnc ...
#define xlfCoupncd ...
#define xlfCoupnum ...
#define xlfCouppcd ...
#define xlfDuration ...
#define xlfMduration ...
#define xlfOddlprice ...
#define xlfOddlyield ...
#define xlfOddfprice ...
#define xlfOddfyield ...
#define xlfRandbetween ...
#define xlfWeeknum ...
#define xlfAmordegrc ...
#define xlfAmorlinc ...
#define xlfConvert ...
#define xlfAccrint ...
#define xlfAccrintm ...
#define xlfWorkday ...
#define xlfNetworkdays ...
#define xlfGcd ...
#define xlfMultinomial ...
#define xlfLcm ...
#define xlfFvschedule ...
#define xlfCubekpimember ...
#define xlfCubeset ...
#define xlfCubesetcount ...
#define xlfIferror ...
#define xlfCountifs ...
#define xlfSumifs ...
#define xlfAverageif ...
#define xlfAverageifs ...
#define xlfAggregate ...
#define xlfBinom_dist ...
#define xlfBinom_inv ...
#define xlfConfidence_norm ...
#define xlfConfidence_t ...
#define xlfChisq_test ...
#define xlfF_test ...
#define xlfCovariance_p ...
#define xlfCovariance_s ...
#define xlfExpon_dist ...
#define xlfGamma_dist ...
#define xlfGamma_inv ...
#define xlfMode_mult ...
#define xlfMode_sngl ...
#define xlfNorm_dist ...
#define xlfNorm_inv ...
#define xlfPercentile_exc ...
#define xlfPercentile_inc ...
#define xlfPercentrank_exc ...
#define xlfPercentrank_inc ...
#define xlfPoisson_dist ...
#define xlfQuartile_exc ...
#define xlfQuartile_inc ...
#define xlfRank_avg ...
#define xlfRank_eq ...
#define xlfStdev_s ...
#define xlfStdev_p ...
#define xlfT_dist ...
#define xlfT_dist_2t ...
#define xlfT_dist_rt ...
#define xlfT_inv ...
#define xlfT_inv_2t ...
#define xlfVar_s ...
#define xlfVar_p ...
#define xlfWeibull_dist ...
#define xlfNetworkdays_intl ...
#define xlfWorkday_intl ...
#define xlfEcma_ceiling ...
#define xlfIso_ceiling ...
#define xlfBeta_dist ...
#define xlfBeta_inv ...
#define xlfChisq_dist ...
#define xlfChisq_dist_rt ...
#define xlfChisq_inv ...
#define xlfChisq_inv_rt ...
#define xlfF_dist ...
#define xlfF_dist_rt ...
#define xlfF_inv ...
#define xlfF_inv_rt ...
#define xlfHypgeom_dist ...
#define xlfLognorm_dist ...
#define xlfLognorm_inv ...
#define xlfNegbinom_dist ...
#define xlfNorm_s_dist ...
#define xlfNorm_s_inv ...
#define xlfT_test ...
#define xlfZ_test ...
#define xlfErf_precise ...
#define xlfErfc_precise ...
#define xlfGammaln_precise ...
#define xlfCeiling_precise ...
#define xlfFloor_precise ...
#define xlfAcot ...
#define xlfAcoth ...
#define xlfCot ...
#define xlfCoth ...
#define xlfCsc ...
#define xlfCsch ...
#define xlfSec ...
#define xlfSech ...
#define xlfImtan ...
#define xlfImcot ...
#define xlfImcsc ...
#define xlfImcsch ...
#define xlfImsec ...
#define xlfImsech ...
#define xlfBitand ...
#define xlfBitor ...
#define xlfBitxor ...
#define xlfBitlshift ...
#define xlfBitrshift ...
#define xlfPermutationa ...
#define xlfCombina ...
#define xlfXor ...
#define xlfPduration ...
#define xlfBase ...
#define xlfDecimal ...
#define xlfDays ...
#define xlfBinom_dist_range ...
#define xlfGamma ...
#define xlfSkew_p ...
#define xlfGauss ...
#define xlfPhi ...
#define xlfRri ...
#define xlfUnichar ...
#define xlfUnicode ...
#define xlfMunit ...
#define xlfArabic ...
#define xlfIsoweeknum ...
#define xlfNumbervalue ...
#define xlfSheet ...
#define xlfSheets ...
#define xlfFormulatext ...
#define xlfIsformula ...
#define xlfIfna ...
#define xlfCeiling_math ...
#define xlfFloor_math ...
#define xlfImsinh ...
#define xlfImcosh ...
#define xlfFilterxml ...
#define xlfWebservice ...
#define xlfEncodeurl ...

/* Excel command numbers */
#define xlcBeep ...
#define xlcOpen ...
#define xlcOpenLinks ...
#define xlcCloseAll ...
#define xlcSave ...
#define xlcSaveAs ...
#define xlcFileDelete ...
#define xlcPageSetup ...
#define xlcPrint ...
#define xlcPrinterSetup ...
#define xlcQuit ...
#define xlcNewWindow ...
#define xlcArrangeAll ...
#define xlcWindowSize ...
#define xlcWindowMove ...
#define xlcFull ...
#define xlcClose ...
#define xlcRun ...
#define xlcSetPrintArea ...
#define xlcSetPrintTitles ...
#define xlcSetPageBreak ...
#define xlcRemovePageBreak ...
#define xlcFont ...
#define xlcDisplay ...
#define xlcProtectDocument ...
#define xlcPrecision ...
#define xlcA1R1c1 ...
#define xlcCalculateNow ...
#define xlcCalculation ...
#define xlcDataFind ...
#define xlcExtract ...
#define xlcDataDelete ...
#define xlcSetDatabase ...
#define xlcSetCriteria ...
#define xlcSort ...
#define xlcDataSeries ...
#define xlcTable ...
#define xlcFormatNumber ...
#define xlcAlignment ...
#define xlcStyle ...
#define xlcBorder ...
#define xlcCellProtection ...
#define xlcColumnWidth ...
#define xlcUndo ...
#define xlcCut ...
#define xlcCopy ...
#define xlcPaste ...
#define xlcClear ...
#define xlcPasteSpecial ...
#define xlcEditDelete ...
#define xlcInsert ...
#define xlcFillRight ...
#define xlcFillDown ...
#define xlcDefineName ...
#define xlcCreateNames ...
#define xlcFormulaGoto ...
#define xlcFormulaFind ...
#define xlcSelectLastCell ...
#define xlcShowActiveCell ...
#define xlcGalleryArea ...
#define xlcGalleryBar ...
#define xlcGalleryColumn ...
#define xlcGalleryLine ...
#define xlcGalleryPie ...
#define xlcGalleryScatter ...
#define xlcCombination ...
#define xlcPreferred ...
#define xlcAddOverlay ...
#define xlcGridlines ...
#define xlcSetPreferred ...
#define xlcAxes ...
#define xlcLegend ...
#define xlcAttachText ...
#define xlcAddArrow ...
#define xlcSelectChart ...
#define xlcSelectPlotArea ...
#define xlcPatterns ...
#define xlcMainChart ...
#define xlcOverlay ...
#define xlcScale ...
#define xlcFormatLegend ...
#define xlcFormatText ...
#define xlcEditRepeat ...
#define xlcParse ...
#define xlcJustify ...
#define xlcHide ...
#define xlcUnhide ...
#define xlcWorkspace ...
#define xlcFormula ...
#define xlcFormulaFill ...
#define xlcFormulaArray ...
#define xlcDataFindNext ...
#define xlcDataFindPrev ...
#define xlcFormulaFindNext ...
#define xlcFormulaFindPrev ...
#define xlcActivate ...
#define xlcActivateNext ...
#define xlcActivatePrev ...
#define xlcUnlockedNext ...
#define xlcUnlockedPrev ...
#define xlcCopyPicture ...
#define xlcSelect ...
#define xlcDeleteName ...
#define xlcDeleteFormat ...
#define xlcVline ...
#define xlcHline ...
#define xlcVpage ...
#define xlcHpage ...
#define xlcVscroll ...
#define xlcHscroll ...
#define xlcAlert ...
#define xlcNew ...
#define xlcCancelCopy ...
#define xlcShowClipboard ...
#define xlcMessage ...
#define xlcPasteLink ...
#define xlcAppActivate ...
#define xlcDeleteArrow ...
#define xlcRowHeight ...
#define xlcFormatMove ...
#define xlcFormatSize ...
#define xlcFormulaReplace ...
#define xlcSendKeys ...
#define xlcSelectSpecial ...
#define xlcApplyNames ...
#define xlcReplaceFont ...
#define xlcFreezePanes ...
#define xlcShowInfo ...
#define xlcSplit ...
#define xlcOnWindow ...
#define xlcOnData ...
#define xlcDisableInput ...
#define xlcEcho ...
#define xlcOutline ...
#define xlcListNames ...
#define xlcFileClose ...
#define xlcSaveWorkbook ...
#define xlcDataForm ...
#define xlcCopyChart ...
#define xlcOnTime ...
#define xlcWait ...
#define xlcFormatFont ...
#define xlcFillUp ...
#define xlcFillLeft ...
#define xlcDeleteOverlay ...
#define xlcNote ...
#define xlcShortMenus ...
#define xlcSetUpdateStatus ...
#define xlcColorPalette ...
#define xlcDeleteStyle ...
#define xlcWindowRestore ...
#define xlcWindowMaximize ...
#define xlcError ...
#define xlcChangeLink ...
#define xlcCalculateDocument ...
#define xlcOnKey ...
#define xlcAppRestore ...
#define xlcAppMove ...
#define xlcAppSize ...
#define xlcAppMinimize ...
#define xlcAppMaximize ...
#define xlcBringToFront ...
#define xlcSendToBack ...
#define xlcMainChartType ...
#define xlcOverlayChartType ...
#define xlcSelectEnd ...
#define xlcOpenMail ...
#define xlcSendMail ...
#define xlcStandardFont ...
#define xlcConsolidate ...
#define xlcSortSpecial ...
#define xlcGallery3dArea ...
#define xlcGallery3dColumn ...
#define xlcGallery3dLine ...
#define xlcGallery3dPie ...
#define xlcView3d ...
#define xlcGoalSeek ...
#define xlcWorkgroup ...
#define xlcFillGroup ...
#define xlcUpdateLink ...
#define xlcPromote ...
#define xlcDemote ...
#define xlcShowDetail ...
#define xlcUngroup ...
#define xlcObjectProperties ...
#define xlcSaveNewObject ...
#define xlcShare ...
#define xlcShareName ...
#define xlcDuplicate ...
#define xlcApplyStyle ...
#define xlcAssignToObject ...
#define xlcObjectProtection ...
#define xlcHideObject ...
#define xlcSetExtract ...
#define xlcCreatePublisher ...
#define xlcSubscribeTo ...
#define xlcAttributes ...
#define xlcShowToolbar ...
#define xlcPrintPreview ...
#define xlcEditColor ...
#define xlcShowLevels ...
#define xlcFormatMain ...
#define xlcFormatOverlay ...
#define xlcOnRecalc ...
#define xlcEditSeries ...
#define xlcDefineStyle ...
#define xlcLinePrint ...
#define xlcEnterData ...
#define xlcGalleryRadar ...
#define xlcMergeStyles ...
#define xlcEditionOptions ...
#define xlcPastePicture ...
#define xlcPastePictureLink ...
#define xlcSpelling ...
#define xlcZoom ...
#define xlcResume ...
#define xlcInsertObject ...
#define xlcWindowMinimize ...
#define xlcSize ...
#define xlcMove ...
#define xlcSoundNote ...
#define xlcSoundPlay ...
#define xlcFormatShape ...
#define xlcExtendPolygon ...
#define xlcFormatAuto ...
#define xlcGallery3dBar ...
#define xlcGallery3dSurface ...
#define xlcFillAuto ...
#define xlcCustomizeToolbar ...
#define xlcAddTool ...
#define xlcEditObject ...
#define xlcOnDoubleclick ...
#define xlcOnEntry ...
#define xlcWorkbookAdd ...
#define xlcWorkbookMove ...
#define xlcWorkbookCopy ...
#define xlcWorkbookOptions ...
#define xlcSaveWorkspace ...
#define xlcChartWizard ...
#define xlcDeleteTool ...
#define xlcMoveTool ...
#define xlcWorkbookSelect ...
#define xlcWorkbookActivate ...
#define xlcAssignToTool ...
#define xlcCopyTool ...
#define xlcResetTool ...
#define xlcConstrainNumeric ...
#define xlcPasteTool ...
#define xlcPlacement ...
#define xlcFillWorkgroup ...
#define xlcWorkbookNew ...
#define xlcScenarioCells ...
#define xlcScenarioDelete ...
#define xlcScenarioAdd ...
#define xlcScenarioEdit ...
#define xlcScenarioShow ...
#define xlcScenarioShowNext ...
#define xlcScenarioSummary ...
#define xlcPivotTableWizard ...
#define xlcPivotFieldProperties ...
#define xlcPivotField ...
#define xlcPivotItem ...
#define xlcPivotAddFields ...
#define xlcOptionsCalculation ...
#define xlcOptionsEdit ...
#define xlcOptionsView ...
#define xlcAddinManager ...
#define xlcMenuEditor ...
#define xlcAttachToolbars ...
#define xlcVbaactivate ...
#define xlcOptionsChart ...
#define xlcVbaInsertFile ...
#define xlcVbaProcedureDefinition ...
#define xlcRoutingSlip ...
#define xlcRouteDocument ...
#define xlcMailLogon ...
#define xlcInsertPicture ...
#define xlcEditTool ...
#define xlcGalleryDoughnut ...
#define xlcChartTrend ...
#define xlcPivotItemProperties ...
#define xlcWorkbookInsert ...
#define xlcOptionsTransition ...
#define xlcOptionsGeneral ...
#define xlcFilterAdvanced ...
#define xlcMailAddMailer ...
#define xlcMailDeleteMailer ...
#define xlcMailReply ...
#define xlcMailReplyAll ...
#define xlcMailForward ...
#define xlcMailNextLetter ...
#define xlcDataLabel ...
#define xlcInsertTitle ...
#define xlcFontProperties ...
#define xlcMacroOptions ...
#define xlcWorkbookHide ...
#define xlcWorkbookUnhide ...
#define xlcWorkbookDelete ...
#define xlcWorkbookName ...
#define xlcGalleryCustom ...
#define xlcAddChartAutoformat ...
#define xlcDeleteChartAutoformat ...
#define xlcChartAddData ...
#define xlcAutoOutline ...
#define xlcTabOrder ...
#define xlcShowDialog ...
#define xlcSelectAll ...
#define xlcUngroupSheets ...
#define xlcSubtotalCreate ...
#define xlcSubtotalRemove ...
#define xlcRenameObject ...
#define xlcWorkbookScroll ...
#define xlcWorkbookNext ...
#define xlcWorkbookPrev ...
#define xlcWorkbookTabSplit ...
#define xlcFullScreen ...
#define xlcWorkbookProtect ...
#define xlcScrollbarProperties ...
#define xlcPivotShowPages ...
#define xlcTextToColumns ...
#define xlcFormatCharttype ...
#define xlcLinkFormat ...
#define xlcTracerDisplay ...
#define xlcTracerNavigate ...
#define xlcTracerClear ...
#define xlcTracerError ...
#define xlcPivotFieldGroup ...
#define xlcPivotFieldUngroup ...
#define xlcCheckboxProperties ...
#define xlcLabelProperties ...
#define xlcListboxProperties ...
#define xlcEditboxProperties ...
#define xlcPivotRefresh ...
#define xlcLinkCombo ...
#define xlcOpenText ...
#define xlcHideDialog ...
#define xlcSetDialogFocus ...
#define xlcEnableObject ...
#define xlcPushbuttonProperties ...
#define xlcSetDialogDefault ...
#define xlcFilter ...
#define xlcFilterShowAll ...
#define xlcClearOutline ...
#define xlcFunctionWizard ...
#define xlcAddListItem ...
#define xlcSetListItem ...
#define xlcRemoveListItem ...
#define xlcSelectListItem ...
#define xlcSetControlValue ...
#define xlcSaveCopyAs ...
#define xlcOptionsListsAdd ...
#define xlcOptionsListsDelete ...
#define xlcSeriesAxes ...
#define xlcSeriesX ...
#define xlcSeriesY ...
#define xlcErrorbarX ...
#define xlcErrorbarY ...
#define xlcFormatChart ...
#define xlcSeriesOrder ...
#define xlcMailLogoff ...
#define xlcClearRoutingSlip ...
#define xlcAppActivateMicrosoft ...
#define xlcMailEditMailer ...
#define xlcOnSheet ...
#define xlcStandardWidth ...
#define xlcScenarioMerge ...
#define xlcSummaryInfo ...
#define xlcFindFile ...
#define xlcActiveCellFont ...
#define xlcEnableTipwizard ...
#define xlcVbaMakeAddin ...
#define xlcInsertdatatable ...
#define xlcWorkgroupOptions ...
#define xlcMailSendMailer ...
#define xlcAutocorrect ...
#define xlcPostDocument ...
#define xlcPicklist ...
#define xlcViewShow ...
#define xlcViewDefine ...
#define xlcViewDelete ...
#define xlcSheetBackground ...
#define xlcInsertMapObject ...
#define xlcOptionsMenono ...
#define xlcNormal ...
#define xlcLayout ...
#define xlcRmPrintArea ...
#define xlcClearPrintArea ...
#define xlcAddPrintArea ...
#define xlcMoveBrk ...
#define xlcHidecurrNote ...
#define xlcHideallNotes ...
#define xlcDeleteNote ...
#define xlcTraverseNotes ...
#define xlcActivateNotes ...
#define xlcProtectRevisions ...
#define xlcUnprotectRevisions ...
#define xlcOptionsMe ...
#define xlcWebPublish ...
#define xlcNewwebquery ...
#define xlcPivotTableChart ...
#define xlcOptionsSave ...
#define xlcOptionsSpell ...
#define xlcHideallInkannots ...

